### ISSUE TITLE
Arch version updating; kyberorg seems to only offer three latest versions.

### ISSUE THREAD

**Issue by Thommenius** [ouspg/vms#2]
As the [kyberorg mirror](https://arch.kyberorg.fi/iso/) seems to hold only the last three versions of arch, the install script is going to be broken or in need of updating every time they lose the version coded in.  
- Update manually every time
- Automate it to change version
- Switch to using [latest](https://arch.kyberorg.fi/iso/latest/)

Which would be the preferred way? Latest seems smartest, however might introduce incompatibilities?

The file [archlinux.pkr.hcl](https://github.com/ouspg/vms/blob/main/archlinux.pkr.hcl) lines 69 & 70,  
```
  iso_url = "https://arch.kyberorg.fi/iso/2023.03.01/archlinux-2023.03.01-x86_64.iso"
  iso_checksum = "file:https://arch.kyberorg.fi/iso/2023.03.01/sha256sums.txt"
```

Currently newest version would be [2023.06.01](https://arch.kyberorg.fi/iso/2023.06.01/).

2023.03.1 is not available anymore, this breaks the script.

**Comment by Nicceboy** [comment]
Using the latest one should be fine, since we want to provide latest software and we run the builder when we want to upgrade everything.

On the other hand, it might not be a big problem to update manually, since we haven't automatically building these yet.

If there is option to use latest, maybe we could try to use that one?
